# Site settings
title: JE Bennett Law
email: me@timbrazier.co.uk
description: > # this means to ignore newlines until "baseurl:"
  JE Bennett Law is a Limited company incorporated in England and Wales (No.7875908), and is authorised and regulated by the Solicitors Regulation Authority (No.565975)
baseurl: "/jebennettlaw.co.uk" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
sass:
style: compressed
